#cloud-config
package_update: true
package_upgrade: true

packages:
  - curl
  - wget
  - jq
  - python

runcmd:
  - | 
     # Install Azure CLI
     curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash